name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      # 기존 Docker 컨테이너 및 이미지 삭제
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f dweb

      # Docker Hub에서 최신 Docker 이미지 가져오기
      - name: Pull Docker Image from Docker hub
        run: sudo docker pull dweblab/songdo:latest

      # Docker 컨테이너 실행
      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name dweb dweblab/songdo:latest
