name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Git 리포지토리를 체크아웃
      - uses: actions/checkout@v4

      # Node.js 20.x 설치 및 npm 캐시 설정
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      # 의존성 설치
      - run: npm ci

      # QEMU 설정 (다중 아키텍처 빌드를 위한 준비)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker Buildx 설정 (다중 아키텍처 빌드를 지원하는 Docker 빌더)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t dweblab/songdo .

      # Docker 이미지 푸시
      - name: Push docker image
        run: docker push dweblab/songdo:latest
